apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen3-mcp-server
spec:
  template:
    spec:
      containers:
      - name: mcp-server
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen3-nginx
spec:
  template:
    spec:
      containers:
      - name: nginx
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
