apiVersion: v1
kind: Secret
metadata:
  name: qwen3-mcp-secrets
  labels:
    app: qwen3-mcp
type: Opaque
stringData:
  # Base64 encode your actual API key before deployment
  openrouter-api-key: "your-openrouter-api-key-here"
  # Redis connection string (if using external Redis)
  redis-url: "redis://redis-service:6379"
  # Database connection (if needed)
  database-url: "postgresql://user:pass@postgres-service:5432/qwen3db"
